"""add graph node layout table

Revision ID: 0cf75c57ee2d
Revises: 727b10a87024
Create Date: 2026-03-27 20:15:10.088185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf75c57ee2d'
down_revision: Union[str, None] = '727b10a87024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_node_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('vx', sa.Float(), nullable=False),
    sa.Column('vy', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_node_layouts_node_key'), 'graph_node_layouts', ['node_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_node_layouts_node_key'), table_name='graph_node_layouts')
    op.drop_table('graph_node_layouts')
    # ### end Alembic commands ###
