"""Initial migration

Revision ID: 3eb60c527a8b
Revises:
Create Date: 2026-03-25 17:08:28.136082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3eb60c527a8b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("benchmark_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_benchmarks_name"), "benchmarks", ["name"], unique=False)
    op.create_table(
        "coverage_maps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("total_evidence_count", sa.Integer(), nullable=False),
        sa.Column("high_tier_evidence_count", sa.Integer(), nullable=False),
        sa.Column("contradiction_count", sa.Integer(), nullable=False),
        sa.Column("unresolved_contradiction_count", sa.Integer(), nullable=False),
        sa.Column(
            "evidence_class_coverage_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("overall_coverage_score", sa.Float(), nullable=False),
        sa.Column("last_computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coverage_maps_subject_id"),
        "coverage_maps",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coverage_maps_subject_type"),
        "coverage_maps",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "dossiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("executive_summary", sa.String(), nullable=True),
        sa.Column("business_model", sa.String(), nullable=True),
        sa.Column("bull_case", sa.String(), nullable=True),
        sa.Column("bear_case", sa.String(), nullable=True),
        sa.Column("key_drivers", sa.String(), nullable=True),
        sa.Column("competitor_landscape", sa.String(), nullable=True),
        sa.Column("active_contradictions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dossiers_subject_id"), "dossiers", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_dossiers_subject_type"), "dossiers", ["subject_type"], unique=False
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=True),
        sa.Column(
            "properties_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edges_relationship_type"), "edges", ["relationship_type"], unique=False
    )
    op.create_index(op.f("ix_edges_source_id"), "edges", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_edges_source_type"), "edges", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_edges_target_id"), "edges", ["target_id"], unique=False)
    op.create_index(
        op.f("ix_edges_target_type"), "edges", ["target_type"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_table(
        "evidence_importance_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("importance", sa.String(), nullable=False),
        sa.Column("directness", sa.String(), nullable=False),
        sa.Column("novelty", sa.String(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_importance_scores_composite_score"),
        "evidence_importance_scores",
        ["composite_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_importance_scores_evidence_id"),
        "evidence_importance_scores",
        ["evidence_id"],
        unique=False,
    )
    op.create_table(
        "evidence_packets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assembled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("query_text", sa.String(), nullable=True),
        sa.Column("subject_type", sa.String(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("direct_evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("connected_evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "historical_evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=True
        ),
        sa.Column(
            "contradiction_evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=True
        ),
        sa.Column("lesson_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "portfolio_context_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "coverage_map_snapshot_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "retrieval_layers_used", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("gap_flags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("total_token_estimate", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_promotion_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("min_tier_for_conclusion_change", sa.String(), nullable=False),
        sa.Column("min_supporting_items", sa.Integer(), nullable=False),
        sa.Column("min_distinct_sources", sa.Integer(), nullable=False),
        sa.Column("repeated_weak_equals_strong", sa.Boolean(), nullable=False),
        sa.Column("require_contradiction_check", sa.Boolean(), nullable=False),
        sa.Column("require_benchmark_confounder_check", sa.Boolean(), nullable=False),
        sa.Column("require_macro_confounder_check", sa.Boolean(), nullable=False),
        sa.Column(
            "tier_weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "experiment_family_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "trigger_conditions_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_name"),
    )
    op.create_table(
        "graph_traversal_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("root_node_type", sa.String(), nullable=False),
        sa.Column("root_node_id", sa.UUID(), nullable=False),
        sa.Column("traversal_depth", sa.Integer(), nullable=False),
        sa.Column(
            "filter_params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("node_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("edge_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historical_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("episode_type", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("affected_sectors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("affected_themes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("dominant_channel", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_episodes_episode_type"),
        "historical_episodes",
        ["episode_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_episodes_name"),
        "historical_episodes",
        ["name"],
        unique=False,
    )
    op.create_table(
        "inference_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("log_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("total_calls", sa.Integer(), nullable=False),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inference_logs_log_date"), "inference_logs", ["log_date"], unique=False
    )
    op.create_index(
        op.f("ix_inference_logs_model_name"),
        "inference_logs",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inference_logs_task_type"),
        "inference_logs",
        ["task_type"],
        unique=False,
    )
    op.create_table(
        "inference_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("model_tier", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("max_input_tokens", sa.Integer(), nullable=True),
        sa.Column("max_output_tokens", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("enable_caching", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inference_policies_task_type"),
        "inference_policies",
        ["task_type"],
        unique=True,
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("lesson_type", sa.String(), nullable=False),
        sa.Column("applicable_sectors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("applicable_regimes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("originating_decision_review_id", sa.UUID(), nullable=True),
        sa.Column("originating_experiment_result_id", sa.UUID(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manual_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("override_type", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "new_state_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manual_overrides_target_id"),
        "manual_overrides",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_manual_overrides_target_type"),
        "manual_overrides",
        ["target_type"],
        unique=False,
    )
    op.create_table(
        "market_calendar",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exchange_code", sa.String(), nullable=False),
        sa.Column("calendar_date", sa.Date(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("is_half_day", sa.Boolean(), nullable=False),
        sa.Column("holiday_name", sa.String(), nullable=True),
        sa.Column("open_time_utc", sa.String(), nullable=True),
        sa.Column("close_time_utc", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_calendar_calendar_date"),
        "market_calendar",
        ["calendar_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_calendar_exchange_code"),
        "market_calendar",
        ["exchange_code"],
        unique=False,
    )
    op.create_table(
        "regime_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("regime_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("signal_source", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_regime_states_regime_type"),
        "regime_states",
        ["regime_type"],
        unique=False,
    )
    op.create_table(
        "research_trigger_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("coverage_thin_weight", sa.Float(), nullable=False),
        sa.Column("contradiction_high_weight", sa.Float(), nullable=False),
        sa.Column("stake_large_weight", sa.Float(), nullable=False),
        sa.Column("source_trust_weak_weight", sa.Float(), nullable=False),
        sa.Column("event_ambiguity_high_weight", sa.Float(), nullable=False),
        sa.Column("benchmark_confounder_weight", sa.Float(), nullable=False),
        sa.Column("trigger_threshold", sa.Float(), nullable=False),
        sa.Column("max_research_budget_usd", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "retrieval_budgets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_type", sa.String(), nullable=False),
        sa.Column("max_direct_items", sa.Integer(), nullable=False),
        sa.Column("max_connected_items", sa.Integer(), nullable=False),
        sa.Column("max_historical_items", sa.Integer(), nullable=False),
        sa.Column("max_contradiction_items", sa.Integer(), nullable=False),
        sa.Column("max_total_items", sa.Integer(), nullable=False),
        sa.Column("max_total_tokens", sa.Integer(), nullable=False),
        sa.Column("expansion_allowed", sa.Boolean(), nullable=False),
        sa.Column("max_expansion_rounds", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_budgets_run_type"),
        "retrieval_budgets",
        ["run_type"],
        unique=True,
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=False)
    op.create_index(
        op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False
    )
    op.create_table(
        "dossier_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("executive_summary", sa.String(), nullable=True),
        sa.Column("snapshot_reason", sa.String(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dossier_snapshots_dossier_id"),
        "dossier_snapshots",
        ["dossier_id"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("is_evolving", sa.Boolean(), nullable=False),
        sa.Column("parent_event_id", sa.UUID(), nullable=True),
        sa.Column("historical_episode_id", sa.UUID(), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("public_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reasoned_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eligible_action_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["historical_episode_id"],
            ["historical_episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_events_title"), "events", ["title"], unique=False)
    op.create_table(
        "missing_evidence_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coverage_map_id", sa.UUID(), nullable=False),
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("importance_to_thesis", sa.String(), nullable=False),
        sa.Column("identified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["coverage_map_id"],
            ["coverage_maps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_missing_evidence_classes_coverage_map_id"),
        "missing_evidence_classes",
        ["coverage_map_id"],
        unique=False,
    )
    op.create_table(
        "raw_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_item_type", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("raw_content_ref", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("public_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reasoned_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eligible_action_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_evidence_external_id"),
        "raw_evidence",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_evidence_source_id"), "raw_evidence", ["source_id"], unique=False
    )
    op.create_table(
        "reasoning_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_packet_id", sa.UUID(), nullable=True),
        sa.Column("run_type", sa.String(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("output_text", sa.String(), nullable=True),
        sa.Column(
            "structured_output_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_packet_id"],
            ["evidence_packets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reasoning_runs_run_type"), "reasoning_runs", ["run_type"], unique=False
    )
    op.create_table(
        "securities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("instrument_type", sa.String(), nullable=False),
        sa.Column("share_class", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("cusip", sa.String(), nullable=True),
        sa.Column("multiplier", sa.Numeric(), nullable=True),
        sa.Column("underlying_security_id", sa.UUID(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("strike_price", sa.Numeric(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("delisted_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["underlying_security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cusip"),
        sa.UniqueConstraint("isin"),
    )
    op.create_index(
        op.f("ix_securities_asset_class"), "securities", ["asset_class"], unique=False
    )
    op.create_index(
        op.f("ix_securities_entity_id"), "securities", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_securities_ticker"), "securities", ["ticker"], unique=False
    )
    op.create_table(
        "shadow_experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("policy_description", sa.String(), nullable=False),
        sa.Column("start_point", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_point", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "initial_portfolio_state_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "final_portfolio_state_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("run_status", sa.String(), nullable=False),
        sa.Column("skip_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["experiment_family_states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_performance_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("regime", sa.String(), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_claims", sa.Integer(), nullable=False),
        sa.Column("correct_claims", sa.Integer(), nullable=False),
        sa.Column("incorrect_claims", sa.Integer(), nullable=False),
        sa.Column("accuracy_rate", sa.Float(), nullable=False),
        sa.Column("originality_rate", sa.Float(), nullable=False),
        sa.Column("timing_score", sa.Float(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_performance_history_source_id"),
        "source_performance_history",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "source_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("specialization_domains", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("known_weaknesses", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("trust_trajectory", sa.String(), nullable=False),
        sa.Column("first_tracked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_claims_tracked", sa.Integer(), nullable=False),
        sa.Column("active_since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_profiles_source_id"),
        "source_profiles",
        ["source_id"],
        unique=True,
    )
    op.create_table(
        "source_quality_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("horizon", sa.String(), nullable=True),
        sa.Column("regime", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("quality_score", sa.Numeric(), nullable=False),
        sa.Column("originality_score", sa.Numeric(), nullable=False),
        sa.Column("timing_usefulness", sa.Numeric(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("last_evaluated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_count", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_quality_segments_source_id"),
        "source_quality_segments",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "source_trust_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("factual_reliability", sa.String(), nullable=False),
        sa.Column("calibration", sa.String(), nullable=False),
        sa.Column("correction_quality", sa.String(), nullable=False),
        sa.Column("noise_ratio", sa.String(), nullable=False),
        sa.Column("trust_trajectory", sa.String(), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_trust_profiles_source_id"),
        "source_trust_profiles",
        ["source_id"],
        unique=True,
    )
    op.create_table(
        "source_value_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("idea_generation_value", sa.String(), nullable=False),
        sa.Column("timing_value", sa.String(), nullable=False),
        sa.Column("portfolio_relevance_value", sa.String(), nullable=False),
        sa.Column("specificity", sa.String(), nullable=False),
        sa.Column("originality", sa.String(), nullable=False),
        sa.Column("best_domains", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_value_profiles_source_id"),
        "source_value_profiles",
        ["source_id"],
        unique=True,
    )
    op.create_table(
        "unresolved_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coverage_map_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=False),
        sa.Column("urgency", sa.Integer(), nullable=False),
        sa.Column("originating_evidence_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coverage_map_id"],
            ["coverage_maps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unresolved_questions_coverage_map_id"),
        "unresolved_questions",
        ["coverage_map_id"],
        unique=False,
    )
    op.create_table(
        "benchmark_constituents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=False),
        sa.Column("weight_pct", sa.Float(), nullable=False),
        sa.Column("as_of_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmarks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_benchmark_constituents_benchmark_id"),
        "benchmark_constituents",
        ["benchmark_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benchmark_constituents_security_id"),
        "benchmark_constituents",
        ["security_id"],
        unique=False,
    )
    op.create_table(
        "critique_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=False),
        sa.Column("critique_text", sa.String(), nullable=False),
        sa.Column("issues_found", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_critique_runs_reasoning_run_id"),
        "critique_runs",
        ["reasoning_run_id"],
        unique=False,
    )
    op.create_table(
        "dossier_deltas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("evidence_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.Column("summary_of_changes", sa.String(), nullable=False),
        sa.Column("sections_modified", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dossier_deltas_dossier_id"),
        "dossier_deltas",
        ["dossier_id"],
        unique=False,
    )
    op.create_table(
        "experiment_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("shadow_return", sa.Float(), nullable=False),
        sa.Column("actual_return", sa.Float(), nullable=False),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("max_drawdown", sa.Float(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["shadow_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_results_experiment_id"),
        "experiment_results",
        ["experiment_id"],
        unique=True,
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("avg_cost_basis", sa.Numeric(), nullable=False),
        sa.Column("current_price", sa.Numeric(), nullable=False),
        sa.Column("market_value", sa.Numeric(), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(), nullable=False),
        sa.Column("weight_pct", sa.Numeric(), nullable=False),
        sa.Column("notional_exposure", sa.Numeric(), nullable=True),
        sa.Column("delta_exposure", sa.Numeric(), nullable=True),
        sa.Column("is_nonlinear", sa.Boolean(), nullable=False),
        sa.Column("thesis_id", sa.UUID(), nullable=True),
        sa.Column("conviction", sa.Integer(), nullable=True),
        sa.Column("list_type", sa.String(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_urgency", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_positions_list_type"), "positions", ["list_type"], unique=False
    )
    op.create_index(
        op.f("ix_positions_security_id"), "positions", ["security_id"], unique=False
    )
    op.create_table(
        "resolutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unresolved_question_id", sa.UUID(), nullable=True),
        sa.Column("missing_evidence_class_id", sa.UUID(), nullable=True),
        sa.Column("resolving_evidence_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["missing_evidence_class_id"],
            ["missing_evidence_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unresolved_question_id"],
            ["unresolved_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review_queue_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("size_factor", sa.Float(), nullable=False),
        sa.Column("evidence_change_factor", sa.Float(), nullable=False),
        sa.Column("contradiction_pressure", sa.Float(), nullable=False),
        sa.Column("thesis_drift", sa.Float(), nullable=False),
        sa.Column("catalyst_proximity", sa.Float(), nullable=False),
        sa.Column("coverage_weakness", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger_reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_queue_items_item_id"),
        "review_queue_items",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_queue_items_item_type"),
        "review_queue_items",
        ["item_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_queue_items_priority_score"),
        "review_queue_items",
        ["priority_score"],
        unique=False,
    )
    op.create_table(
        "scenario_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("scenario_description", sa.String(), nullable=False),
        sa.Column(
            "shock_parameters_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "portfolio_impact_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("total_portfolio_impact", sa.Float(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shadow_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("simulated_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["shadow_experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shadow_actions_experiment_id"),
        "shadow_actions",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "source_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_evidence_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("extracted_text", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_evidence_id"],
            ["raw_evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_evidence_id"),
    )
    op.create_index(
        op.f("ix_source_items_source_id"), "source_items", ["source_id"], unique=False
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("triggering_event_id", sa.UUID(), nullable=True),
        sa.Column("tagged_security_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["triggering_event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_themes_name"), "themes", ["name"], unique=False)
    op.create_table(
        "attribution_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("portfolio_wide", sa.Boolean(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_return", sa.Float(), nullable=False),
        sa.Column("factor_return", sa.Float(), nullable=False),
        sa.Column("idiosyncratic_return", sa.Float(), nullable=False),
        sa.Column(
            "factor_contributions_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attribution_results_position_id"),
        "attribution_results",
        ["position_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.String(), nullable=False),
        sa.Column("claim_type", sa.String(), nullable=False),
        sa.Column("claimant", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("sentiment", sa.String(), nullable=True),
        sa.Column("source_item_id", sa.UUID(), nullable=False),
        sa.Column("is_original", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("importance", sa.String(), nullable=False),
        sa.Column("directness", sa.String(), nullable=False),
        sa.Column("novelty", sa.String(), nullable=False),
        sa.Column("contradiction_role", sa.String(), nullable=False),
        sa.Column("promotion_eligible", sa.Boolean(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("public_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reasoned_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eligible_action_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_item_id"],
            ["source_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claims_claim_type"), "claims", ["claim_type"], unique=False
    )
    op.create_index(
        op.f("ix_claims_source_item_id"), "claims", ["source_item_id"], unique=False
    )
    op.create_index(op.f("ix_claims_tier"), "claims", ["tier"], unique=False)
    op.create_table(
        "factor_exposures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("portfolio_wide", sa.Boolean(), nullable=False),
        sa.Column("factor_name", sa.String(), nullable=False),
        sa.Column("exposure_value", sa.Float(), nullable=False),
        sa.Column("as_of_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_factor_exposures_factor_name"),
        "factor_exposures",
        ["factor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factor_exposures_position_id"),
        "factor_exposures",
        ["position_id"],
        unique=False,
    )
    op.create_table(
        "facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.String(), nullable=False),
        sa.Column("fact_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("source_item_id", sa.UUID(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("importance", sa.String(), nullable=False),
        sa.Column("directness", sa.String(), nullable=False),
        sa.Column("novelty", sa.String(), nullable=False),
        sa.Column("contradiction_role", sa.String(), nullable=False),
        sa.Column("promotion_eligible", sa.Boolean(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("public_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reasoned_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eligible_action_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_item_id"],
            ["source_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_facts_fact_type"), "facts", ["fact_type"], unique=False)
    op.create_index(
        op.f("ix_facts_source_item_id"), "facts", ["source_item_id"], unique=False
    )
    op.create_index(op.f("ix_facts_tier"), "facts", ["tier"], unique=False)
    op.create_table(
        "lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("cost_basis", sa.Numeric(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lot_type", sa.String(), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lots_position_id"), "lots", ["position_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_position_id"),
        "transactions",
        ["position_id"],
        unique=False,
    )
    op.create_table(
        "implications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trigger_event_id", sa.UUID(), nullable=True),
        sa.Column("trigger_fact_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=False),
        sa.Column("overall_time_horizon", sa.String(), nullable=False),
        sa.Column("already_priced_in_assessment", sa.String(), nullable=False),
        sa.Column("affected_positions", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("affected_watchlist", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("affected_themes", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("affected_benchmarks", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_fact_id"],
            ["facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_claim_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("regime", sa.String(), nullable=True),
        sa.Column("claim_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assessment", sa.String(), nullable=False),
        sa.Column("assessment_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessment_evidence", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_claim_records_claim_id"),
        "source_claim_records",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_claim_records_source_id"),
        "source_claim_records",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "impact_channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("implication_id", sa.UUID(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("magnitude", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("time_horizon", sa.String(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.Column("order_num", sa.String(), nullable=False),
        sa.Column("competing_with_channel_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competing_with_channel_id"],
            ["impact_channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["implication_id"],
            ["implications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_impact_channels_implication_id"),
        "impact_channels",
        ["implication_id"],
        unique=False,
    )
    op.create_table(
        "priced_in_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("implication_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=True),
        sa.Column("assessment", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.Column("price_move_observed", sa.Float(), nullable=True),
        sa.Column("price_move_expected", sa.Float(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["implication_id"],
            ["implications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_priced_in_assessments_implication_id"),
        "priced_in_assessments",
        ["implication_id"],
        unique=False,
    )
    op.create_table(
        "channel_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("implication_id", sa.UUID(), nullable=False),
        sa.Column("dominant_channel_id", sa.UUID(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("distinguishing_evidence_needed", sa.String(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dominant_channel_id"],
            ["impact_channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["implication_id"],
            ["implications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_assessments_implication_id"),
        "channel_assessments",
        ["implication_id"],
        unique=False,
    )
    op.create_table(
        "conclusion_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("current_thesis_summary", sa.String(), nullable=False),
        sa.Column("current_stance", sa.String(), nullable=False),
        sa.Column("confidence_band", sa.String(), nullable=False),
        sa.Column("dominant_channel_id", sa.UUID(), nullable=True),
        sa.Column("key_supporting_evidence_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("key_contradicting_evidence_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("what_would_falsify", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("what_would_strengthen", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_count", sa.Integer(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dominant_channel_id"],
            ["impact_channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conclusion_states_subject_id"),
        "conclusion_states",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conclusion_states_subject_type"),
        "conclusion_states",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "conclusion_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conclusion_state_id", sa.UUID(), nullable=False),
        sa.Column("previous_stance", sa.String(), nullable=False),
        sa.Column("new_stance", sa.String(), nullable=False),
        sa.Column("previous_confidence", sa.String(), nullable=False),
        sa.Column("new_confidence", sa.String(), nullable=False),
        sa.Column("trigger_evidence_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("revision_reasoning", sa.String(), nullable=False),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=False),
        sa.Column("revised_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conclusion_state_id"],
            ["conclusion_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conclusion_revisions_conclusion_state_id"),
        "conclusion_revisions",
        ["conclusion_state_id"],
        unique=False,
    )
    op.create_table(
        "decision_journals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("decision_type", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("expected_catalyst_timeframe", sa.String(), nullable=True),
        sa.Column("expected_return", sa.Float(), nullable=True),
        sa.Column("conclusion_state_id", sa.UUID(), nullable=True),
        sa.Column("evidence_packet_id", sa.UUID(), nullable=True),
        sa.Column("dossier_version_id", sa.UUID(), nullable=True),
        sa.Column("transaction_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conclusion_state_id"],
            ["conclusion_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_packet_id"],
            ["evidence_packets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_journals_decision_type"),
        "decision_journals",
        ["decision_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_journals_position_id"),
        "decision_journals",
        ["position_id"],
        unique=False,
    )
    op.create_table(
        "theses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("theme_id", sa.UUID(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("catalysts", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("risks", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("base_target", sa.Float(), nullable=True),
        sa.Column("bull_target", sa.Float(), nullable=True),
        sa.Column("bear_target", sa.Float(), nullable=True),
        sa.Column("time_horizon_months", sa.Integer(), nullable=True),
        sa.Column("conclusion_state_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conclusion_state_id"],
            ["conclusion_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_theses_entity_id"), "theses", ["entity_id"], unique=False)
    op.create_index(op.f("ix_theses_theme_id"), "theses", ["theme_id"], unique=False)
    op.create_table(
        "decision_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("decision_journal_id", sa.UUID(), nullable=False),
        sa.Column("outcome_assessment", sa.String(), nullable=False),
        sa.Column("actual_return", sa.Float(), nullable=True),
        sa.Column("mistake_preventable", sa.Boolean(), nullable=True),
        sa.Column("what_went_right", sa.String(), nullable=True),
        sa.Column("what_went_wrong", sa.String(), nullable=True),
        sa.Column("what_to_improve", sa.String(), nullable=True),
        sa.Column("reasoning_run_id", sa.UUID(), nullable=True),
        sa.Column("extracted_lesson_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_journal_id"],
            ["decision_journals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_run_id"],
            ["reasoning_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_reviews_decision_journal_id"),
        "decision_reviews",
        ["decision_journal_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_decision_reviews_decision_journal_id"), table_name="decision_reviews"
    )
    op.drop_table("decision_reviews")
    op.drop_index(op.f("ix_theses_theme_id"), table_name="theses")
    op.drop_index(op.f("ix_theses_entity_id"), table_name="theses")
    op.drop_table("theses")
    op.drop_index(
        op.f("ix_decision_journals_position_id"), table_name="decision_journals"
    )
    op.drop_index(
        op.f("ix_decision_journals_decision_type"), table_name="decision_journals"
    )
    op.drop_table("decision_journals")
    op.drop_index(
        op.f("ix_conclusion_revisions_conclusion_state_id"),
        table_name="conclusion_revisions",
    )
    op.drop_table("conclusion_revisions")
    op.drop_index(
        op.f("ix_conclusion_states_subject_type"), table_name="conclusion_states"
    )
    op.drop_index(
        op.f("ix_conclusion_states_subject_id"), table_name="conclusion_states"
    )
    op.drop_table("conclusion_states")
    op.drop_index(
        op.f("ix_channel_assessments_implication_id"), table_name="channel_assessments"
    )
    op.drop_table("channel_assessments")
    op.drop_index(
        op.f("ix_priced_in_assessments_implication_id"),
        table_name="priced_in_assessments",
    )
    op.drop_table("priced_in_assessments")
    op.drop_index(
        op.f("ix_impact_channels_implication_id"), table_name="impact_channels"
    )
    op.drop_table("impact_channels")
    op.drop_index(
        op.f("ix_source_claim_records_source_id"), table_name="source_claim_records"
    )
    op.drop_index(
        op.f("ix_source_claim_records_claim_id"), table_name="source_claim_records"
    )
    op.drop_table("source_claim_records")
    op.drop_table("implications")
    op.drop_index(op.f("ix_transactions_position_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_lots_position_id"), table_name="lots")
    op.drop_table("lots")
    op.drop_index(op.f("ix_facts_tier"), table_name="facts")
    op.drop_index(op.f("ix_facts_source_item_id"), table_name="facts")
    op.drop_index(op.f("ix_facts_fact_type"), table_name="facts")
    op.drop_table("facts")
    op.drop_index(
        op.f("ix_factor_exposures_position_id"), table_name="factor_exposures"
    )
    op.drop_index(
        op.f("ix_factor_exposures_factor_name"), table_name="factor_exposures"
    )
    op.drop_table("factor_exposures")
    op.drop_index(op.f("ix_claims_tier"), table_name="claims")
    op.drop_index(op.f("ix_claims_source_item_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_claim_type"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(
        op.f("ix_attribution_results_position_id"), table_name="attribution_results"
    )
    op.drop_table("attribution_results")
    op.drop_index(op.f("ix_themes_name"), table_name="themes")
    op.drop_table("themes")
    op.drop_index(op.f("ix_source_items_source_id"), table_name="source_items")
    op.drop_table("source_items")
    op.drop_index(op.f("ix_shadow_actions_experiment_id"), table_name="shadow_actions")
    op.drop_table("shadow_actions")
    op.drop_table("scenario_analyses")
    op.drop_index(
        op.f("ix_review_queue_items_priority_score"), table_name="review_queue_items"
    )
    op.drop_index(
        op.f("ix_review_queue_items_item_type"), table_name="review_queue_items"
    )
    op.drop_index(
        op.f("ix_review_queue_items_item_id"), table_name="review_queue_items"
    )
    op.drop_table("review_queue_items")
    op.drop_table("resolutions")
    op.drop_index(op.f("ix_positions_security_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_list_type"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(
        op.f("ix_experiment_results_experiment_id"), table_name="experiment_results"
    )
    op.drop_table("experiment_results")
    op.drop_index(op.f("ix_dossier_deltas_dossier_id"), table_name="dossier_deltas")
    op.drop_table("dossier_deltas")
    op.drop_index(op.f("ix_critique_runs_reasoning_run_id"), table_name="critique_runs")
    op.drop_table("critique_runs")
    op.drop_index(
        op.f("ix_benchmark_constituents_security_id"),
        table_name="benchmark_constituents",
    )
    op.drop_index(
        op.f("ix_benchmark_constituents_benchmark_id"),
        table_name="benchmark_constituents",
    )
    op.drop_table("benchmark_constituents")
    op.drop_index(
        op.f("ix_unresolved_questions_coverage_map_id"),
        table_name="unresolved_questions",
    )
    op.drop_table("unresolved_questions")
    op.drop_index(
        op.f("ix_source_value_profiles_source_id"), table_name="source_value_profiles"
    )
    op.drop_table("source_value_profiles")
    op.drop_index(
        op.f("ix_source_trust_profiles_source_id"), table_name="source_trust_profiles"
    )
    op.drop_table("source_trust_profiles")
    op.drop_index(
        op.f("ix_source_quality_segments_source_id"),
        table_name="source_quality_segments",
    )
    op.drop_table("source_quality_segments")
    op.drop_index(op.f("ix_source_profiles_source_id"), table_name="source_profiles")
    op.drop_table("source_profiles")
    op.drop_index(
        op.f("ix_source_performance_history_source_id"),
        table_name="source_performance_history",
    )
    op.drop_table("source_performance_history")
    op.drop_table("shadow_experiments")
    op.drop_index(op.f("ix_securities_ticker"), table_name="securities")
    op.drop_index(op.f("ix_securities_entity_id"), table_name="securities")
    op.drop_index(op.f("ix_securities_asset_class"), table_name="securities")
    op.drop_table("securities")
    op.drop_index(op.f("ix_reasoning_runs_run_type"), table_name="reasoning_runs")
    op.drop_table("reasoning_runs")
    op.drop_index(op.f("ix_raw_evidence_source_id"), table_name="raw_evidence")
    op.drop_index(op.f("ix_raw_evidence_external_id"), table_name="raw_evidence")
    op.drop_table("raw_evidence")
    op.drop_index(
        op.f("ix_missing_evidence_classes_coverage_map_id"),
        table_name="missing_evidence_classes",
    )
    op.drop_table("missing_evidence_classes")
    op.drop_index(op.f("ix_events_title"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        op.f("ix_dossier_snapshots_dossier_id"), table_name="dossier_snapshots"
    )
    op.drop_table("dossier_snapshots")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_index(op.f("ix_sources_name"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_retrieval_budgets_run_type"), table_name="retrieval_budgets")
    op.drop_table("retrieval_budgets")
    op.drop_table("research_trigger_policies")
    op.drop_index(op.f("ix_regime_states_regime_type"), table_name="regime_states")
    op.drop_table("regime_states")
    op.drop_index(
        op.f("ix_market_calendar_exchange_code"), table_name="market_calendar"
    )
    op.drop_index(
        op.f("ix_market_calendar_calendar_date"), table_name="market_calendar"
    )
    op.drop_table("market_calendar")
    op.drop_index(
        op.f("ix_manual_overrides_target_type"), table_name="manual_overrides"
    )
    op.drop_index(op.f("ix_manual_overrides_target_id"), table_name="manual_overrides")
    op.drop_table("manual_overrides")
    op.drop_table("lessons")
    op.drop_index(
        op.f("ix_inference_policies_task_type"), table_name="inference_policies"
    )
    op.drop_table("inference_policies")
    op.drop_index(op.f("ix_inference_logs_task_type"), table_name="inference_logs")
    op.drop_index(op.f("ix_inference_logs_model_name"), table_name="inference_logs")
    op.drop_index(op.f("ix_inference_logs_log_date"), table_name="inference_logs")
    op.drop_table("inference_logs")
    op.drop_index(op.f("ix_historical_episodes_name"), table_name="historical_episodes")
    op.drop_index(
        op.f("ix_historical_episodes_episode_type"), table_name="historical_episodes"
    )
    op.drop_table("historical_episodes")
    op.drop_table("graph_traversal_sets")
    op.drop_table("experiment_family_states")
    op.drop_table("evidence_promotion_policies")
    op.drop_table("evidence_packets")
    op.drop_index(
        op.f("ix_evidence_importance_scores_evidence_id"),
        table_name="evidence_importance_scores",
    )
    op.drop_index(
        op.f("ix_evidence_importance_scores_composite_score"),
        table_name="evidence_importance_scores",
    )
    op.drop_table("evidence_importance_scores")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_edges_target_type"), table_name="edges")
    op.drop_index(op.f("ix_edges_target_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_source_type"), table_name="edges")
    op.drop_index(op.f("ix_edges_source_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_relationship_type"), table_name="edges")
    op.drop_table("edges")
    op.drop_index(op.f("ix_dossiers_subject_type"), table_name="dossiers")
    op.drop_index(op.f("ix_dossiers_subject_id"), table_name="dossiers")
    op.drop_table("dossiers")
    op.drop_index(op.f("ix_coverage_maps_subject_type"), table_name="coverage_maps")
    op.drop_index(op.f("ix_coverage_maps_subject_id"), table_name="coverage_maps")
    op.drop_table("coverage_maps")
    op.drop_index(op.f("ix_benchmarks_name"), table_name="benchmarks")
    op.drop_table("benchmarks")
    # ### end Alembic commands ###
