"""add_active_watchers

Revision ID: 58a15deebaf4
Revises: 1a2c5b4d9e77
Create Date: 2026-05-12 10:54:57.865604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a15deebaf4'
down_revision: Union[str, None] = '1a2c5b4d9e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_watchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('adjustment_plan', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_detail', sa.String(), nullable=True),
    sa.Column('action_taken_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_conclusion_states_subject'), 'conclusion_states', type_='unique')
    op.drop_constraint(op.f('uq_coverage_maps_subject'), 'coverage_maps', type_='unique')
    op.drop_constraint(op.f('uq_edges_relationship_tuple'), 'edges', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_edges_relationship_tuple'), 'edges', ['source_type', 'source_id', 'target_type', 'target_id', 'relationship_type'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_coverage_maps_subject'), 'coverage_maps', ['subject_type', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_conclusion_states_subject'), 'conclusion_states', ['subject_type', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('active_watchers')
    # ### end Alembic commands ###
