"""add_cash_ledger

Revision ID: 727b10a87024
Revises: aed93f6471fd
Create Date: 2026-03-27 20:01:57.545939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "727b10a87024"
down_revision: Union[str, None] = "aed93f6471fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("balance_after", sa.Numeric(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("public_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_reasoned_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eligible_action_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cash_ledger_entries_entry_type"),
        "cash_ledger_entries",
        ["entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_ledger_entries_executed_at"),
        "cash_ledger_entries",
        ["executed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_ledger_entries_transaction_id"),
        "cash_ledger_entries",
        ["transaction_id"],
        unique=False,
    )
    op.add_column(
        "transactions",
        sa.Column("status", sa.String(), server_default="settled", nullable=False),
    )
    op.add_column(
        "transactions", sa.Column("superseded_by_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "transactions",
        sa.Column(
            "provenance_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_foreign_key(
        None, "transactions", "transactions", ["superseded_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "provenance_json")
    op.drop_column("transactions", "superseded_by_id")
    op.drop_column("transactions", "status")
    op.drop_index(
        op.f("ix_cash_ledger_entries_transaction_id"), table_name="cash_ledger_entries"
    )
    op.drop_index(
        op.f("ix_cash_ledger_entries_executed_at"), table_name="cash_ledger_entries"
    )
    op.drop_index(
        op.f("ix_cash_ledger_entries_entry_type"), table_name="cash_ledger_entries"
    )
    op.drop_table("cash_ledger_entries")
    # ### end Alembic commands ###
