"""add_knowledge_deprecation

Revision ID: aed93f6471fd
Revises: b7b6f7e6f7c1
Create Date: 2026-03-27 17:49:11.684780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aed93f6471fd"
down_revision: Union[str, None] = "b7b6f7e6f7c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claims", sa.Column("is_deprecated", sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column("claims", sa.Column("deprecated_reason", sa.String(), nullable=True))
    op.add_column("events", sa.Column("is_deprecated", sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column("events", sa.Column("deprecated_reason", sa.String(), nullable=True))
    op.add_column("facts", sa.Column("is_deprecated", sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column("facts", sa.Column("deprecated_reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("facts", "deprecated_reason")
    op.drop_column("facts", "is_deprecated")
    op.drop_column("events", "deprecated_reason")
    op.drop_column("events", "is_deprecated")
    op.drop_column("claims", "deprecated_reason")
    op.drop_column("claims", "is_deprecated")
    # ### end Alembic commands ###
