"""Add horizon columns to knowledge models

Revision ID: e921fa634761
Revises: 0cf75c57ee2d
Create Date: 2026-04-07 01:13:59.560755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e921fa634761'
down_revision: Union[str, None] = '0cf75c57ee2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_names(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {column["name"] for column in inspector.get_columns(table_name)}


def _ensure_column(table_name: str, column: sa.Column) -> None:
    if column.name not in _column_names(table_name):
        op.add_column(table_name, column)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('target_horizon', sa.String(), nullable=False, server_default='strategic'))
    op.add_column('claims', sa.Column('horizon_reasoning', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_claims_target_horizon'), 'claims', ['target_horizon'], unique=False)
    _ensure_column('dossiers', sa.Column('is_autonomous', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    _ensure_column('dossiers', sa.Column('review_status', sa.Text(), nullable=True))
    _ensure_column('dossiers', sa.Column('review_reason', sa.Text(), nullable=True))
    _ensure_column('dossiers', sa.Column('strategist_reasoning', sa.Text(), nullable=True))
    _ensure_column('dossiers', sa.Column('source_rationale', sa.Text(), nullable=True))
    op.alter_column('dossiers', 'is_autonomous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('dossiers', 'review_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dossiers', 'review_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dossiers', 'strategist_reasoning',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dossiers', 'source_rationale',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('events', sa.Column('target_horizon', sa.String(), nullable=False, server_default='strategic'))
    op.add_column('events', sa.Column('horizon_reasoning', sa.String(), nullable=True))
    op.add_column('events', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_events_target_horizon'), 'events', ['target_horizon'], unique=False)
    op.add_column('facts', sa.Column('target_horizon', sa.String(), nullable=False, server_default='strategic'))
    op.add_column('facts', sa.Column('horizon_reasoning', sa.String(), nullable=True))
    op.add_column('facts', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_facts_target_horizon'), 'facts', ['target_horizon'], unique=False)
    _ensure_column('positions', sa.Column('is_autonomous', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    _ensure_column('positions', sa.Column('review_status', sa.Text(), nullable=True))
    op.alter_column('positions', 'is_autonomous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('positions', 'review_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transactions', 'position_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'position_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('positions', 'review_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('positions', 'is_autonomous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_facts_target_horizon'), table_name='facts')
    op.drop_column('facts', 'valid_until')
    op.drop_column('facts', 'horizon_reasoning')
    op.drop_column('facts', 'target_horizon')
    op.drop_index(op.f('ix_events_target_horizon'), table_name='events')
    op.drop_column('events', 'valid_until')
    op.drop_column('events', 'horizon_reasoning')
    op.drop_column('events', 'target_horizon')
    op.alter_column('dossiers', 'source_rationale',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dossiers', 'strategist_reasoning',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dossiers', 'review_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dossiers', 'review_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dossiers', 'is_autonomous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_claims_target_horizon'), table_name='claims')
    op.drop_column('claims', 'valid_until')
    op.drop_column('claims', 'horizon_reasoning')
    op.drop_column('claims', 'target_horizon')
    # ### end Alembic commands ###
