import asyncio
import os
import sys

# Set up paths so we can import investos
sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))

from sqlalchemy import desc, select

from investos.db import async_session_maker, get_session
from investos.models.portfolio import CashLedgerEntry, Transaction
from investos.services.runtime_settings import RuntimeSettingsStore


async def backfill():
    async with async_session_maker() as session:
        # Check if already backfilled
        existing = (
            await session.execute(select(CashLedgerEntry).limit(1))
        ).scalar_one_or_none()
        if existing is not None:
            print("Ledger already populated. Exiting.")
            return

        runtime = RuntimeSettingsStore.load()
        buying_power = runtime.portfolio.remaining_buying_power

        # Fetch all transactions ordered by executed_at asc
        transactions = list(
            (
                await session.execute(
                    select(Transaction).order_by(Transaction.executed_at.asc())
                )
            )
            .scalars()
            .all()
        )

        # Net cash generated by trades
        net_cash_from_trades = 0.0
        for txn in transactions:
            if txn.action == "buy" and txn.price:
                net_cash_from_trades -= float(txn.quantity) * float(txn.price)
            elif txn.action == "sell" and txn.price:
                net_cash_from_trades += float(txn.quantity) * float(txn.price)
            elif txn.action == "dividend" and txn.price:
                net_cash_from_trades += float(
                    txn.price
                )  # usually price represents total dividend amount in this schema

        # We need final balance = buying_power
        # Initial deposit + net_cash_from_trades = buying_power
        # Initial deposit = buying_power - net_cash_from_trades
        initial_deposit_amount = float(buying_power) - net_cash_from_trades

        # Create Initial Deposit
        current_balance = 0.0
        if initial_deposit_amount > 0 or initial_deposit_amount < 0:
            current_balance = initial_deposit_amount
            initial_entry = CashLedgerEntry(
                entry_type="deposit" if initial_deposit_amount >= 0 else "withdrawal",
                amount=initial_deposit_amount,
                balance_after=current_balance,
                description="Auto-backfilled initial capital to match historical buying power",
                executed_at=(
                    transactions[0].executed_at
                    if transactions
                    else runtime.core.created_at
                ),  # Need an earlier time
            )
            session.add(initial_entry)
            print(f"Created initial deposit of {initial_deposit_amount}")

        for txn in transactions:
            amount = 0.0
            if txn.action == "buy" and txn.price:
                amount = -(float(txn.quantity) * float(txn.price))
            elif txn.action == "sell" and txn.price:
                amount = float(txn.quantity) * float(txn.price)
            elif txn.action == "dividend" and txn.price:
                amount = float(txn.price)

            if amount != 0.0:
                current_balance += amount
                entry = CashLedgerEntry(
                    entry_type=(
                        "dividend" if txn.action == "dividend" else "trade_settlement"
                    ),
                    amount=amount,
                    balance_after=current_balance,
                    transaction_id=txn.id,
                    description=f"Auto-backfilled {txn.action}",
                    executed_at=txn.executed_at,
                )
                session.add(entry)

        await session.commit()
        print(
            f"Backfill complete! Final balance computed: {current_balance}, matched required: {buying_power}"
        )


if __name__ == "__main__":
    asyncio.run(backfill())
